### PR TITLE
Minting fee

### PR DESCRIPTION
**Pull request by samsiegart**
fixes https://github.com/Agoric/dapp-inter/issues/247
fixes https://github.com/Agoric/dapp-inter/issues/248

### Adjust Vault Minting Fee Text
image

### Adjust Vault Tooltip + Minting Fee
image

### Create Vault Tooltip
create-vault-tooltip

### CODE REVIEW

**Comment by samsiegart** [comment]
I made some adjustments apart from the latest comment on https://github.com/Agoric/dapp-inter/issues/248.

In particular, in "Adjust Vault", I didn't add the "Minting" line because there's nothing to show on the left of the arrow so it looked odd (we don't know the total amount minted from a particular vault, only its debt). Also, the contents of the tooltip as suggested: `Existing debt (1100) + minting fee (50) + accrued stability fee (X)` didn't seem quite right, because existing debt includes stability fee already, and we need to add the newly minted amount to that equation instead. Also, I didn't include the values because it seemed kinda noisy for a tooltip, but could add them back if needed.

**Comment by otoole-brendan** [comment]
@samsiegart 

Some changes to improve consistency:

Adjust Vault: Change 'Debt' -> 'Your Debt Balance' (tool tip and its contents looks good so let's keep them)

Create Vault: Similarly the tool tip and contents work well here but I noticed the line items for create vault could do with re-ordering to more intuitive and to match 'Adjust Vault'. This includes:

- Move 'Collateralization Ratio' to be above the line
- Move 'Stability Fee' and 'Minimum Collateralization Ratio' below the line.

The rationale with the delineating line was to visually separate the static fees/rates (below the line) and the dynamic/vault-specific information (above the line). This might be a little out of the scope of this change but I think it's easier to address with this PR and does simplify UX nicely

**Comment by samsiegart** [comment]
@otoole-brendan Thanks for taking a look, makes sense. Just adjusted as shown:

image

image

**Review by 0xpatrickdev — APPROVED** [review]

**Comment by otoole-brendan** [comment]
@samsiegart looks good but the order of line items below line for adjust vault and create vault differs. The ordering for adjust vault is best imo so can you change the create vault order to match adjust vault ordering? (just the below the line pieces)

**Comment by samsiegart** [comment]
Updated the ordering in create-vault:

image

**Pull request merged**
