### PR TITLE
build: implement publishing pinning

### PR DESCRIPTION
**Pull request by arirubinstein**
refs https://github.com/Agoric/agoric-sdk/issues/4350

Implements automatic IPFS pinning/publishing for the dapp-inter repo, including PR comments and main comments.

### CODE REVIEW

**Review by samsiegart — COMMENTED** [review]
> IPFS hash: `Qmc36a5q9DuvLr9irYw5vnYmu49Zr6mEEk1yqqqDFaamYC` Gateways:
> 
> * https://cloudflare-ipfs.com/ipfs/Qmc36a5q9DuvLr9irYw5vnYmu49Zr6mEEk1yqqqDFaamYC/
> * https://ipfs.io/ipfs/Qmc36a5q9DuvLr9irYw5vnYmu49Zr6mEEk1yqqqDFaamYC/

I'm not seeing the 404 page like in https://cloudflare-ipfs.com/ipfs/QmcHm8wo6M2TYB9QYhHB4JnMogGT5S3tht6qvBwgPWBh9X/index.html, just a white page. I tried adding index.html to the end to no avail. Is that expected?

**Comment by samsiegart** [comment]
Nit: "build" or "feat" is probably more fitting than "fix"

**Comment by arirubinstein** [comment]
I modified the other example to be rootless, but I got lost at the router.  The assets are there and should work once the paths are fixed.  e.g. https://cloudflare-ipfs.com/ipfs/Qmc36a5q9DuvLr9irYw5vnYmu49Zr6mEEk1yqqqDFaamYC/IST.png

**Comment by samsiegart** [comment]
LGTM thanks! The error page can be fixed by switching to hash routing as part of https://github.com/Agoric/dapp-inter/issues/35

**Review by samsiegart — APPROVED** [review]

**Pull request merged**
